# Generated by Django 5.0.1 on 2024-11-15 09:31

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_invoice_total_alter_product_product_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="item",
            field=models.ForeignKey(
                blank=True,
                default="",
                null=True,
                on_delete=models.SET(core.models.get_sentinel_product),
                to="core.product",
            ),
        ),
    ]
